pub struct Emoji {
    pub character: &'static str,
    pub name: &'static str,
    pub keywords: &'static str,
    pub category: &'static str,
}

pub static EMOJIS: &[Emoji] = &[
    // ── Smileys & Emotion ──────────────────────────────────────────
    Emoji { character: "😀", name: "Grinning Face", keywords: "smile happy cheerful", category: "Smileys & Emotion" },
    Emoji { character: "😃", name: "Grinning Face with Big Eyes", keywords: "smile happy", category: "Smileys & Emotion" },
    Emoji { character: "😄", name: "Grinning Face with Smiling Eyes", keywords: "smile happy laugh", category: "Smileys & Emotion" },
    Emoji { character: "😁", name: "Beaming Face with Smiling Eyes", keywords: "grin happy", category: "Smileys & Emotion" },
    Emoji { character: "😆", name: "Grinning Squinting Face", keywords: "laugh happy lol", category: "Smileys & Emotion" },
    Emoji { character: "😅", name: "Grinning Face with Sweat", keywords: "nervous laugh relief", category: "Smileys & Emotion" },
    Emoji { character: "🤣", name: "Rolling on the Floor Laughing", keywords: "rofl lol hilarious", category: "Smileys & Emotion" },
    Emoji { character: "😂", name: "Face with Tears of Joy", keywords: "laugh cry lol funny", category: "Smileys & Emotion" },
    Emoji { character: "🙂", name: "Slightly Smiling Face", keywords: "smile", category: "Smileys & Emotion" },
    Emoji { character: "🙃", name: "Upside-Down Face", keywords: "sarcasm silly", category: "Smileys & Emotion" },
    Emoji { character: "😉", name: "Winking Face", keywords: "wink flirt", category: "Smileys & Emotion" },
    Emoji { character: "😊", name: "Smiling Face with Smiling Eyes", keywords: "blush happy warm", category: "Smileys & Emotion" },
    Emoji { character: "😇", name: "Smiling Face with Halo", keywords: "angel innocent", category: "Smileys & Emotion" },
    Emoji { character: "🥰", name: "Smiling Face with Hearts", keywords: "love adore crush", category: "Smileys & Emotion" },
    Emoji { character: "😍", name: "Smiling Face with Heart-Eyes", keywords: "love crush infatuation", category: "Smileys & Emotion" },
    Emoji { character: "🤩", name: "Star-Struck", keywords: "excited amazed wow", category: "Smileys & Emotion" },
    Emoji { character: "😘", name: "Face Blowing a Kiss", keywords: "love kiss flirt", category: "Smileys & Emotion" },
    Emoji { character: "😗", name: "Kissing Face", keywords: "kiss", category: "Smileys & Emotion" },
    Emoji { character: "😚", name: "Kissing Face with Closed Eyes", keywords: "kiss love", category: "Smileys & Emotion" },
    Emoji { character: "😙", name: "Kissing Face with Smiling Eyes", keywords: "kiss", category: "Smileys & Emotion" },
    Emoji { character: "🥲", name: "Smiling Face with Tear", keywords: "sad happy bittersweet", category: "Smileys & Emotion" },
    Emoji { character: "😋", name: "Face Savoring Food", keywords: "yummy delicious tasty", category: "Smileys & Emotion" },
    Emoji { character: "😛", name: "Face with Tongue", keywords: "playful silly", category: "Smileys & Emotion" },
    Emoji { character: "😜", name: "Winking Face with Tongue", keywords: "playful silly crazy", category: "Smileys & Emotion" },
    Emoji { character: "🤪", name: "Zany Face", keywords: "crazy wild goofy", category: "Smileys & Emotion" },
    Emoji { character: "😝", name: "Squinting Face with Tongue", keywords: "playful silly", category: "Smileys & Emotion" },
    Emoji { character: "🤑", name: "Money-Mouth Face", keywords: "rich dollar cash", category: "Smileys & Emotion" },
    Emoji { character: "🤗", name: "Smiling Face with Open Hands", keywords: "hug warm", category: "Smileys & Emotion" },
    Emoji { character: "🤭", name: "Face with Hand Over Mouth", keywords: "oops giggle shy", category: "Smileys & Emotion" },
    Emoji { character: "🤫", name: "Shushing Face", keywords: "quiet secret silence", category: "Smileys & Emotion" },
    Emoji { character: "🤔", name: "Thinking Face", keywords: "think hmm wonder ponder", category: "Smileys & Emotion" },
    Emoji { character: "🤐", name: "Zipper-Mouth Face", keywords: "quiet secret mute", category: "Smileys & Emotion" },
    Emoji { character: "🤨", name: "Face with Raised Eyebrow", keywords: "skeptical suspicious doubt", category: "Smileys & Emotion" },
    Emoji { character: "😐", name: "Neutral Face", keywords: "meh indifferent blank", category: "Smileys & Emotion" },
    Emoji { character: "😑", name: "Expressionless Face", keywords: "blank unamused", category: "Smileys & Emotion" },
    Emoji { character: "😶", name: "Face Without Mouth", keywords: "speechless silent", category: "Smileys & Emotion" },
    Emoji { character: "😏", name: "Smirking Face", keywords: "smug flirt suggestive", category: "Smileys & Emotion" },
    Emoji { character: "😒", name: "Unamused Face", keywords: "meh bored annoyed", category: "Smileys & Emotion" },
    Emoji { character: "🙄", name: "Face with Rolling Eyes", keywords: "annoyed whatever", category: "Smileys & Emotion" },
    Emoji { character: "😬", name: "Grimacing Face", keywords: "awkward nervous cringe", category: "Smileys & Emotion" },
    Emoji { character: "🤥", name: "Lying Face", keywords: "pinocchio lie", category: "Smileys & Emotion" },
    Emoji { character: "😌", name: "Relieved Face", keywords: "calm peaceful content", category: "Smileys & Emotion" },
    Emoji { character: "😔", name: "Pensive Face", keywords: "sad thoughtful", category: "Smileys & Emotion" },
    Emoji { character: "😪", name: "Sleepy Face", keywords: "tired sleep", category: "Smileys & Emotion" },
    Emoji { character: "🤤", name: "Drooling Face", keywords: "hungry yummy", category: "Smileys & Emotion" },
    Emoji { character: "😴", name: "Sleeping Face", keywords: "tired sleep zzz", category: "Smileys & Emotion" },
    Emoji { character: "😷", name: "Face with Medical Mask", keywords: "sick ill mask", category: "Smileys & Emotion" },
    Emoji { character: "🤒", name: "Face with Thermometer", keywords: "sick fever ill", category: "Smileys & Emotion" },
    Emoji { character: "🤕", name: "Face with Head-Bandage", keywords: "hurt injured", category: "Smileys & Emotion" },
    Emoji { character: "🤢", name: "Nauseated Face", keywords: "sick vomit disgusted", category: "Smileys & Emotion" },
    Emoji { character: "🤮", name: "Face Vomiting", keywords: "sick throw up puke", category: "Smileys & Emotion" },
    Emoji { character: "🥵", name: "Hot Face", keywords: "heat warm sweating", category: "Smileys & Emotion" },
    Emoji { character: "🥶", name: "Cold Face", keywords: "freezing frozen ice", category: "Smileys & Emotion" },
    Emoji { character: "🥴", name: "Woozy Face", keywords: "drunk tipsy dizzy", category: "Smileys & Emotion" },
    Emoji { character: "😵", name: "Face with Crossed-Out Eyes", keywords: "dizzy dead knocked out", category: "Smileys & Emotion" },
    Emoji { character: "🤯", name: "Exploding Head", keywords: "mind blown shocked", category: "Smileys & Emotion" },
    Emoji { character: "🤠", name: "Cowboy Hat Face", keywords: "western cowboy", category: "Smileys & Emotion" },
    Emoji { character: "🥳", name: "Partying Face", keywords: "party celebrate birthday", category: "Smileys & Emotion" },
    Emoji { character: "🥸", name: "Disguised Face", keywords: "glasses mustache incognito", category: "Smileys & Emotion" },
    Emoji { character: "😎", name: "Smiling Face with Sunglasses", keywords: "cool sunglasses", category: "Smileys & Emotion" },
    Emoji { character: "🤓", name: "Nerd Face", keywords: "geek glasses smart", category: "Smileys & Emotion" },
    Emoji { character: "🧐", name: "Face with Monocle", keywords: "smart classy inspect", category: "Smileys & Emotion" },
    Emoji { character: "😕", name: "Confused Face", keywords: "puzzled uncertain", category: "Smileys & Emotion" },
    Emoji { character: "😟", name: "Worried Face", keywords: "nervous concerned", category: "Smileys & Emotion" },
    Emoji { character: "🙁", name: "Slightly Frowning Face", keywords: "sad disappointed", category: "Smileys & Emotion" },
    Emoji { character: "😮", name: "Face with Open Mouth", keywords: "surprised shocked wow", category: "Smileys & Emotion" },
    Emoji { character: "😯", name: "Hushed Face", keywords: "surprised stunned", category: "Smileys & Emotion" },
    Emoji { character: "😲", name: "Astonished Face", keywords: "shocked amazed", category: "Smileys & Emotion" },
    Emoji { character: "😳", name: "Flushed Face", keywords: "embarrassed shy blush", category: "Smileys & Emotion" },
    Emoji { character: "🥺", name: "Pleading Face", keywords: "puppy eyes beg cute", category: "Smileys & Emotion" },
    Emoji { character: "😦", name: "Frowning Face with Open Mouth", keywords: "sad anguish", category: "Smileys & Emotion" },
    Emoji { character: "😧", name: "Anguished Face", keywords: "stunned", category: "Smileys & Emotion" },
    Emoji { character: "😨", name: "Fearful Face", keywords: "scared afraid", category: "Smileys & Emotion" },
    Emoji { character: "😰", name: "Anxious Face with Sweat", keywords: "nervous worried", category: "Smileys & Emotion" },
    Emoji { character: "😥", name: "Sad but Relieved Face", keywords: "disappointed phew", category: "Smileys & Emotion" },
    Emoji { character: "😢", name: "Crying Face", keywords: "sad tear", category: "Smileys & Emotion" },
    Emoji { character: "😭", name: "Loudly Crying Face", keywords: "sob sad wail", category: "Smileys & Emotion" },
    Emoji { character: "😱", name: "Face Screaming in Fear", keywords: "scared horror omg", category: "Smileys & Emotion" },
    Emoji { character: "😖", name: "Confounded Face", keywords: "frustrated quiver", category: "Smileys & Emotion" },
    Emoji { character: "😣", name: "Persevering Face", keywords: "struggle frustrated", category: "Smileys & Emotion" },
    Emoji { character: "😞", name: "Disappointed Face", keywords: "sad", category: "Smileys & Emotion" },
    Emoji { character: "😓", name: "Downcast Face with Sweat", keywords: "hard work tired", category: "Smileys & Emotion" },
    Emoji { character: "😩", name: "Weary Face", keywords: "tired fed up", category: "Smileys & Emotion" },
    Emoji { character: "😫", name: "Tired Face", keywords: "exhausted sick", category: "Smileys & Emotion" },
    Emoji { character: "🥱", name: "Yawning Face", keywords: "tired bored sleepy", category: "Smileys & Emotion" },
    Emoji { character: "😤", name: "Face with Steam from Nose", keywords: "angry frustrated triumph", category: "Smileys & Emotion" },
    Emoji { character: "😡", name: "Pouting Face", keywords: "angry mad rage red", category: "Smileys & Emotion" },
    Emoji { character: "😠", name: "Angry Face", keywords: "mad annoyed", category: "Smileys & Emotion" },
    Emoji { character: "🤬", name: "Face with Symbols on Mouth", keywords: "swearing cursing angry", category: "Smileys & Emotion" },
    Emoji { character: "😈", name: "Smiling Face with Horns", keywords: "devil evil naughty", category: "Smileys & Emotion" },
    Emoji { character: "👿", name: "Angry Face with Horns", keywords: "devil evil", category: "Smileys & Emotion" },
    Emoji { character: "💀", name: "Skull", keywords: "dead death skeleton", category: "Smileys & Emotion" },
    Emoji { character: "☠️", name: "Skull and Crossbones", keywords: "dead death danger poison", category: "Smileys & Emotion" },
    Emoji { character: "💩", name: "Pile of Poo", keywords: "poop shit crap", category: "Smileys & Emotion" },
    Emoji { character: "🤡", name: "Clown Face", keywords: "clown joker", category: "Smileys & Emotion" },
    Emoji { character: "👹", name: "Ogre", keywords: "monster demon", category: "Smileys & Emotion" },
    Emoji { character: "👻", name: "Ghost", keywords: "halloween spooky", category: "Smileys & Emotion" },
    Emoji { character: "👽", name: "Alien", keywords: "ufo extraterrestrial space", category: "Smileys & Emotion" },
    Emoji { character: "👾", name: "Alien Monster", keywords: "game space invader pixel", category: "Smileys & Emotion" },
    Emoji { character: "🤖", name: "Robot", keywords: "bot machine", category: "Smileys & Emotion" },
    Emoji { character: "💋", name: "Kiss Mark", keywords: "lips love", category: "Smileys & Emotion" },
    Emoji { character: "💯", name: "Hundred Points", keywords: "perfect score 100", category: "Smileys & Emotion" },
    Emoji { character: "💢", name: "Anger Symbol", keywords: "angry mad", category: "Smileys & Emotion" },
    Emoji { character: "💥", name: "Collision", keywords: "boom crash bang explosion", category: "Smileys & Emotion" },
    Emoji { character: "💫", name: "Dizzy", keywords: "star sparkle", category: "Smileys & Emotion" },
    Emoji { character: "💦", name: "Sweat Droplets", keywords: "water splash", category: "Smileys & Emotion" },
    Emoji { character: "💨", name: "Dashing Away", keywords: "wind fast running", category: "Smileys & Emotion" },
    Emoji { character: "🕳️", name: "Hole", keywords: "void empty", category: "Smileys & Emotion" },
    Emoji { character: "💬", name: "Speech Balloon", keywords: "chat comment talk bubble", category: "Smileys & Emotion" },
    Emoji { character: "💭", name: "Thought Balloon", keywords: "think bubble cloud", category: "Smileys & Emotion" },
    Emoji { character: "💤", name: "ZZZ", keywords: "sleep tired", category: "Smileys & Emotion" },
    // ── Hearts & Love ──────────────────────────────────────────────
    Emoji { character: "❤️", name: "Red Heart", keywords: "love like valentines", category: "Smileys & Emotion" },
    Emoji { character: "🧡", name: "Orange Heart", keywords: "love", category: "Smileys & Emotion" },
    Emoji { character: "💛", name: "Yellow Heart", keywords: "love", category: "Smileys & Emotion" },
    Emoji { character: "💚", name: "Green Heart", keywords: "love", category: "Smileys & Emotion" },
    Emoji { character: "💙", name: "Blue Heart", keywords: "love", category: "Smileys & Emotion" },
    Emoji { character: "💜", name: "Purple Heart", keywords: "love", category: "Smileys & Emotion" },
    Emoji { character: "🖤", name: "Black Heart", keywords: "love dark", category: "Smileys & Emotion" },
    Emoji { character: "🤍", name: "White Heart", keywords: "love pure", category: "Smileys & Emotion" },
    Emoji { character: "🤎", name: "Brown Heart", keywords: "love", category: "Smileys & Emotion" },
    Emoji { character: "💔", name: "Broken Heart", keywords: "sad love heartbreak", category: "Smileys & Emotion" },
    Emoji { character: "❤️‍🔥", name: "Heart on Fire", keywords: "love passion", category: "Smileys & Emotion" },
    Emoji { character: "💕", name: "Two Hearts", keywords: "love pair", category: "Smileys & Emotion" },
    Emoji { character: "💖", name: "Sparkling Heart", keywords: "love shine", category: "Smileys & Emotion" },
    Emoji { character: "💗", name: "Growing Heart", keywords: "love", category: "Smileys & Emotion" },
    Emoji { character: "💝", name: "Heart with Ribbon", keywords: "love valentine gift", category: "Smileys & Emotion" },
    // ── Hands & Gestures ───────────────────────────────────────────
    Emoji { character: "👋", name: "Waving Hand", keywords: "hello goodbye wave hi bye", category: "People & Body" },
    Emoji { character: "🤚", name: "Raised Back of Hand", keywords: "stop", category: "People & Body" },
    Emoji { character: "🖐️", name: "Hand with Fingers Splayed", keywords: "high five stop", category: "People & Body" },
    Emoji { character: "✋", name: "Raised Hand", keywords: "high five stop", category: "People & Body" },
    Emoji { character: "🖖", name: "Vulcan Salute", keywords: "spock star trek", category: "People & Body" },
    Emoji { character: "👌", name: "OK Hand", keywords: "okay perfect fine", category: "People & Body" },
    Emoji { character: "🤌", name: "Pinched Fingers", keywords: "italian what chef", category: "People & Body" },
    Emoji { character: "🤏", name: "Pinching Hand", keywords: "small tiny little", category: "People & Body" },
    Emoji { character: "✌️", name: "Victory Hand", keywords: "peace two", category: "People & Body" },
    Emoji { character: "🤞", name: "Crossed Fingers", keywords: "luck hope", category: "People & Body" },
    Emoji { character: "🤟", name: "Love-You Gesture", keywords: "love rock", category: "People & Body" },
    Emoji { character: "🤘", name: "Sign of the Horns", keywords: "rock metal", category: "People & Body" },
    Emoji { character: "🤙", name: "Call Me Hand", keywords: "shaka phone hang loose", category: "People & Body" },
    Emoji { character: "👈", name: "Backhand Index Pointing Left", keywords: "left direction", category: "People & Body" },
    Emoji { character: "👉", name: "Backhand Index Pointing Right", keywords: "right direction", category: "People & Body" },
    Emoji { character: "👆", name: "Backhand Index Pointing Up", keywords: "up direction", category: "People & Body" },
    Emoji { character: "🖕", name: "Middle Finger", keywords: "rude flip off", category: "People & Body" },
    Emoji { character: "👇", name: "Backhand Index Pointing Down", keywords: "down direction", category: "People & Body" },
    Emoji { character: "☝️", name: "Index Pointing Up", keywords: "one up", category: "People & Body" },
    Emoji { character: "👍", name: "Thumbs Up", keywords: "like approve good yes agree", category: "People & Body" },
    Emoji { character: "👎", name: "Thumbs Down", keywords: "dislike bad no disagree", category: "People & Body" },
    Emoji { character: "✊", name: "Raised Fist", keywords: "power strong", category: "People & Body" },
    Emoji { character: "👊", name: "Oncoming Fist", keywords: "punch fist bump", category: "People & Body" },
    Emoji { character: "🤛", name: "Left-Facing Fist", keywords: "fist bump", category: "People & Body" },
    Emoji { character: "🤜", name: "Right-Facing Fist", keywords: "fist bump", category: "People & Body" },
    Emoji { character: "👏", name: "Clapping Hands", keywords: "clap applause bravo", category: "People & Body" },
    Emoji { character: "🙌", name: "Raising Hands", keywords: "celebrate hooray praise", category: "People & Body" },
    Emoji { character: "👐", name: "Open Hands", keywords: "jazz hands", category: "People & Body" },
    Emoji { character: "🤲", name: "Palms Up Together", keywords: "prayer cupped", category: "People & Body" },
    Emoji { character: "🤝", name: "Handshake", keywords: "deal agreement", category: "People & Body" },
    Emoji { character: "🙏", name: "Folded Hands", keywords: "pray please thank you hope namaste", category: "People & Body" },
    Emoji { character: "✍️", name: "Writing Hand", keywords: "write note", category: "People & Body" },
    Emoji { character: "💪", name: "Flexed Biceps", keywords: "strong muscle arm workout", category: "People & Body" },
    Emoji { character: "🦾", name: "Mechanical Arm", keywords: "robot prosthetic", category: "People & Body" },
    Emoji { character: "🦿", name: "Mechanical Leg", keywords: "robot prosthetic", category: "People & Body" },
    Emoji { character: "🦵", name: "Leg", keywords: "kick limb", category: "People & Body" },
    Emoji { character: "🦶", name: "Foot", keywords: "kick stomp", category: "People & Body" },
    Emoji { character: "👂", name: "Ear", keywords: "hear listen sound", category: "People & Body" },
    Emoji { character: "👃", name: "Nose", keywords: "smell sniff", category: "People & Body" },
    Emoji { character: "🧠", name: "Brain", keywords: "smart intelligent mind think", category: "People & Body" },
    Emoji { character: "👀", name: "Eyes", keywords: "look see watch stare", category: "People & Body" },
    Emoji { character: "👁️", name: "Eye", keywords: "look see", category: "People & Body" },
    Emoji { character: "👅", name: "Tongue", keywords: "taste lick", category: "People & Body" },
    Emoji { character: "👄", name: "Mouth", keywords: "lips kiss", category: "People & Body" },
    // ── People ─────────────────────────────────────────────────────
    Emoji { character: "👶", name: "Baby", keywords: "child infant newborn", category: "People & Body" },
    Emoji { character: "👧", name: "Girl", keywords: "child female young", category: "People & Body" },
    Emoji { character: "👦", name: "Boy", keywords: "child male young", category: "People & Body" },
    Emoji { character: "👩", name: "Woman", keywords: "female adult", category: "People & Body" },
    Emoji { character: "👨", name: "Man", keywords: "male adult", category: "People & Body" },
    Emoji { character: "🧑", name: "Person", keywords: "adult gender neutral", category: "People & Body" },
    Emoji { character: "👴", name: "Old Man", keywords: "elderly grandpa", category: "People & Body" },
    Emoji { character: "👵", name: "Old Woman", keywords: "elderly grandma", category: "People & Body" },
    Emoji { character: "🧑‍💻", name: "Technologist", keywords: "programmer developer coder engineer", category: "People & Body" },
    Emoji { character: "🧑‍🔬", name: "Scientist", keywords: "research lab chemist", category: "People & Body" },
    Emoji { character: "🧑‍🎨", name: "Artist", keywords: "painter creative design", category: "People & Body" },
    Emoji { character: "🧑‍🚀", name: "Astronaut", keywords: "space rocket nasa", category: "People & Body" },
    Emoji { character: "🧑‍🍳", name: "Cook", keywords: "chef food kitchen", category: "People & Body" },
    Emoji { character: "🧑‍🏫", name: "Teacher", keywords: "professor educator school", category: "People & Body" },
    Emoji { character: "🧑‍⚕️", name: "Health Worker", keywords: "doctor nurse medical", category: "People & Body" },
    Emoji { character: "🏃", name: "Person Running", keywords: "run sprint jog exercise", category: "People & Body" },
    Emoji { character: "🚶", name: "Person Walking", keywords: "walk stroll pedestrian", category: "People & Body" },
    Emoji { character: "💃", name: "Woman Dancing", keywords: "dance salsa party", category: "People & Body" },
    Emoji { character: "🕺", name: "Man Dancing", keywords: "dance disco party", category: "People & Body" },
    Emoji { character: "🧘", name: "Person in Lotus Position", keywords: "yoga meditate zen", category: "People & Body" },
    // ── Animals & Nature ───────────────────────────────────────────
    Emoji { character: "🐶", name: "Dog Face", keywords: "puppy pet woof", category: "Animals & Nature" },
    Emoji { character: "🐱", name: "Cat Face", keywords: "kitten pet meow", category: "Animals & Nature" },
    Emoji { character: "🐭", name: "Mouse Face", keywords: "rodent", category: "Animals & Nature" },
    Emoji { character: "🐹", name: "Hamster", keywords: "pet rodent", category: "Animals & Nature" },
    Emoji { character: "🐰", name: "Rabbit Face", keywords: "bunny easter", category: "Animals & Nature" },
    Emoji { character: "🦊", name: "Fox", keywords: "fox face", category: "Animals & Nature" },
    Emoji { character: "🐻", name: "Bear", keywords: "teddy brown", category: "Animals & Nature" },
    Emoji { character: "🐼", name: "Panda", keywords: "bear bamboo", category: "Animals & Nature" },
    Emoji { character: "🐨", name: "Koala", keywords: "australia bear", category: "Animals & Nature" },
    Emoji { character: "🐯", name: "Tiger Face", keywords: "cat wild", category: "Animals & Nature" },
    Emoji { character: "🦁", name: "Lion", keywords: "king jungle cat", category: "Animals & Nature" },
    Emoji { character: "🐮", name: "Cow Face", keywords: "moo farm", category: "Animals & Nature" },
    Emoji { character: "🐷", name: "Pig Face", keywords: "oink farm", category: "Animals & Nature" },
    Emoji { character: "🐸", name: "Frog", keywords: "toad ribbit", category: "Animals & Nature" },
    Emoji { character: "🐵", name: "Monkey Face", keywords: "ape primate", category: "Animals & Nature" },
    Emoji { character: "🙈", name: "See-No-Evil Monkey", keywords: "hide shy cover", category: "Animals & Nature" },
    Emoji { character: "🙉", name: "Hear-No-Evil Monkey", keywords: "ignore cover ears", category: "Animals & Nature" },
    Emoji { character: "🙊", name: "Speak-No-Evil Monkey", keywords: "oops cover mouth", category: "Animals & Nature" },
    Emoji { character: "🐔", name: "Chicken", keywords: "hen farm poultry", category: "Animals & Nature" },
    Emoji { character: "🐧", name: "Penguin", keywords: "arctic cold bird", category: "Animals & Nature" },
    Emoji { character: "🐦", name: "Bird", keywords: "tweet fly", category: "Animals & Nature" },
    Emoji { character: "🦅", name: "Eagle", keywords: "bird freedom america", category: "Animals & Nature" },
    Emoji { character: "🦆", name: "Duck", keywords: "bird quack", category: "Animals & Nature" },
    Emoji { character: "🦉", name: "Owl", keywords: "bird wise night", category: "Animals & Nature" },
    Emoji { character: "🐺", name: "Wolf", keywords: "howl wild", category: "Animals & Nature" },
    Emoji { character: "🐗", name: "Boar", keywords: "pig wild", category: "Animals & Nature" },
    Emoji { character: "🐴", name: "Horse Face", keywords: "pony stallion", category: "Animals & Nature" },
    Emoji { character: "🦄", name: "Unicorn", keywords: "horse magic fantasy rainbow", category: "Animals & Nature" },
    Emoji { character: "🐝", name: "Honeybee", keywords: "bee insect buzz honey", category: "Animals & Nature" },
    Emoji { character: "🪲", name: "Beetle", keywords: "bug insect", category: "Animals & Nature" },
    Emoji { character: "🐛", name: "Bug", keywords: "insect caterpillar", category: "Animals & Nature" },
    Emoji { character: "🦋", name: "Butterfly", keywords: "insect pretty nature", category: "Animals & Nature" },
    Emoji { character: "🐌", name: "Snail", keywords: "slow shell", category: "Animals & Nature" },
    Emoji { character: "🐙", name: "Octopus", keywords: "tentacles sea", category: "Animals & Nature" },
    Emoji { character: "🐠", name: "Tropical Fish", keywords: "ocean sea", category: "Animals & Nature" },
    Emoji { character: "🐟", name: "Fish", keywords: "ocean sea swim", category: "Animals & Nature" },
    Emoji { character: "🐬", name: "Dolphin", keywords: "ocean sea marine", category: "Animals & Nature" },
    Emoji { character: "🐳", name: "Spouting Whale", keywords: "ocean sea", category: "Animals & Nature" },
    Emoji { character: "🦈", name: "Shark", keywords: "fish danger ocean", category: "Animals & Nature" },
    Emoji { character: "🐊", name: "Crocodile", keywords: "alligator reptile", category: "Animals & Nature" },
    Emoji { character: "🐢", name: "Turtle", keywords: "slow shell reptile", category: "Animals & Nature" },
    Emoji { character: "🐍", name: "Snake", keywords: "reptile python", category: "Animals & Nature" },
    Emoji { character: "🦎", name: "Lizard", keywords: "reptile gecko", category: "Animals & Nature" },
    Emoji { character: "🦖", name: "T-Rex", keywords: "dinosaur extinct", category: "Animals & Nature" },
    Emoji { character: "🦕", name: "Sauropod", keywords: "dinosaur brontosaurus", category: "Animals & Nature" },
    Emoji { character: "🐉", name: "Dragon", keywords: "fire fantasy", category: "Animals & Nature" },
    // ── Plants & Flowers ───────────────────────────────────────────
    Emoji { character: "🌸", name: "Cherry Blossom", keywords: "flower spring pink sakura", category: "Animals & Nature" },
    Emoji { character: "🌹", name: "Rose", keywords: "flower love red", category: "Animals & Nature" },
    Emoji { character: "🌻", name: "Sunflower", keywords: "flower sun yellow", category: "Animals & Nature" },
    Emoji { character: "🌺", name: "Hibiscus", keywords: "flower tropical", category: "Animals & Nature" },
    Emoji { character: "🌷", name: "Tulip", keywords: "flower spring", category: "Animals & Nature" },
    Emoji { character: "🌱", name: "Seedling", keywords: "plant grow sprout", category: "Animals & Nature" },
    Emoji { character: "🌲", name: "Evergreen Tree", keywords: "pine tree forest nature", category: "Animals & Nature" },
    Emoji { character: "🌳", name: "Deciduous Tree", keywords: "tree forest nature", category: "Animals & Nature" },
    Emoji { character: "🌴", name: "Palm Tree", keywords: "tropical beach", category: "Animals & Nature" },
    Emoji { character: "🌵", name: "Cactus", keywords: "desert plant", category: "Animals & Nature" },
    Emoji { character: "🍀", name: "Four Leaf Clover", keywords: "luck lucky shamrock irish", category: "Animals & Nature" },
    Emoji { character: "🍁", name: "Maple Leaf", keywords: "fall autumn canada", category: "Animals & Nature" },
    Emoji { character: "🍂", name: "Fallen Leaf", keywords: "fall autumn", category: "Animals & Nature" },
    Emoji { character: "🍃", name: "Leaf Fluttering in Wind", keywords: "nature green", category: "Animals & Nature" },
    Emoji { character: "🪵", name: "Wood", keywords: "log timber lumber", category: "Animals & Nature" },
    Emoji { character: "🍄", name: "Mushroom", keywords: "fungus toadstool", category: "Animals & Nature" },
    // ── Food & Drink ───────────────────────────────────────────────
    Emoji { character: "🍎", name: "Red Apple", keywords: "fruit healthy", category: "Food & Drink" },
    Emoji { character: "🍊", name: "Tangerine", keywords: "orange fruit citrus", category: "Food & Drink" },
    Emoji { character: "🍋", name: "Lemon", keywords: "fruit citrus sour", category: "Food & Drink" },
    Emoji { character: "🍌", name: "Banana", keywords: "fruit", category: "Food & Drink" },
    Emoji { character: "🍉", name: "Watermelon", keywords: "fruit summer", category: "Food & Drink" },
    Emoji { character: "🍇", name: "Grapes", keywords: "fruit wine", category: "Food & Drink" },
    Emoji { character: "🍓", name: "Strawberry", keywords: "fruit berry", category: "Food & Drink" },
    Emoji { character: "🫐", name: "Blueberries", keywords: "fruit berry", category: "Food & Drink" },
    Emoji { character: "🍑", name: "Peach", keywords: "fruit butt", category: "Food & Drink" },
    Emoji { character: "🥭", name: "Mango", keywords: "fruit tropical", category: "Food & Drink" },
    Emoji { character: "🍍", name: "Pineapple", keywords: "fruit tropical", category: "Food & Drink" },
    Emoji { character: "🥑", name: "Avocado", keywords: "fruit food guacamole", category: "Food & Drink" },
    Emoji { character: "🥦", name: "Broccoli", keywords: "vegetable green healthy", category: "Food & Drink" },
    Emoji { character: "🥕", name: "Carrot", keywords: "vegetable orange", category: "Food & Drink" },
    Emoji { character: "🌽", name: "Ear of Corn", keywords: "maize vegetable", category: "Food & Drink" },
    Emoji { character: "🌶️", name: "Hot Pepper", keywords: "chili spicy", category: "Food & Drink" },
    Emoji { character: "🥒", name: "Cucumber", keywords: "vegetable pickle", category: "Food & Drink" },
    Emoji { character: "🍞", name: "Bread", keywords: "toast loaf", category: "Food & Drink" },
    Emoji { character: "🥐", name: "Croissant", keywords: "bread french pastry", category: "Food & Drink" },
    Emoji { character: "🧀", name: "Cheese Wedge", keywords: "dairy cheddar", category: "Food & Drink" },
    Emoji { character: "🍖", name: "Meat on Bone", keywords: "drumstick", category: "Food & Drink" },
    Emoji { character: "🍗", name: "Poultry Leg", keywords: "chicken drumstick", category: "Food & Drink" },
    Emoji { character: "🥩", name: "Cut of Meat", keywords: "steak beef", category: "Food & Drink" },
    Emoji { character: "🥓", name: "Bacon", keywords: "pork meat breakfast", category: "Food & Drink" },
    Emoji { character: "🍔", name: "Hamburger", keywords: "burger fast food", category: "Food & Drink" },
    Emoji { character: "🍟", name: "French Fries", keywords: "chips fast food", category: "Food & Drink" },
    Emoji { character: "🍕", name: "Pizza", keywords: "food italian slice", category: "Food & Drink" },
    Emoji { character: "🌭", name: "Hot Dog", keywords: "food sausage", category: "Food & Drink" },
    Emoji { character: "🥪", name: "Sandwich", keywords: "bread food lunch", category: "Food & Drink" },
    Emoji { character: "🌮", name: "Taco", keywords: "mexican food", category: "Food & Drink" },
    Emoji { character: "🌯", name: "Burrito", keywords: "wrap mexican food", category: "Food & Drink" },
    Emoji { character: "🥗", name: "Green Salad", keywords: "healthy food vegetable", category: "Food & Drink" },
    Emoji { character: "🍝", name: "Spaghetti", keywords: "pasta italian food noodle", category: "Food & Drink" },
    Emoji { character: "🍜", name: "Steaming Bowl", keywords: "noodle ramen soup pho", category: "Food & Drink" },
    Emoji { character: "🍲", name: "Pot of Food", keywords: "stew soup", category: "Food & Drink" },
    Emoji { character: "🍣", name: "Sushi", keywords: "japanese food fish", category: "Food & Drink" },
    Emoji { character: "🍱", name: "Bento Box", keywords: "japanese food lunch", category: "Food & Drink" },
    Emoji { character: "🥟", name: "Dumpling", keywords: "food gyoza", category: "Food & Drink" },
    Emoji { character: "🍳", name: "Cooking", keywords: "egg frying pan breakfast", category: "Food & Drink" },
    Emoji { character: "🍰", name: "Shortcake", keywords: "cake dessert", category: "Food & Drink" },
    Emoji { character: "🎂", name: "Birthday Cake", keywords: "cake party celebration", category: "Food & Drink" },
    Emoji { character: "🧁", name: "Cupcake", keywords: "cake dessert muffin", category: "Food & Drink" },
    Emoji { character: "🍩", name: "Doughnut", keywords: "donut dessert", category: "Food & Drink" },
    Emoji { character: "🍪", name: "Cookie", keywords: "biscuit dessert sweet", category: "Food & Drink" },
    Emoji { character: "🍫", name: "Chocolate Bar", keywords: "candy dessert sweet", category: "Food & Drink" },
    Emoji { character: "🍬", name: "Candy", keywords: "sweet sugar", category: "Food & Drink" },
    Emoji { character: "🍭", name: "Lollipop", keywords: "candy sweet", category: "Food & Drink" },
    Emoji { character: "🍦", name: "Soft Ice Cream", keywords: "dessert cone frozen", category: "Food & Drink" },
    Emoji { character: "☕", name: "Hot Beverage", keywords: "coffee tea cup morning", category: "Food & Drink" },
    Emoji { character: "🍵", name: "Teacup Without Handle", keywords: "tea green matcha", category: "Food & Drink" },
    Emoji { character: "🥤", name: "Cup with Straw", keywords: "soda drink juice", category: "Food & Drink" },
    Emoji { character: "🧃", name: "Beverage Box", keywords: "juice box drink", category: "Food & Drink" },
    Emoji { character: "🍺", name: "Beer Mug", keywords: "drink alcohol pub bar", category: "Food & Drink" },
    Emoji { character: "🍻", name: "Clinking Beer Mugs", keywords: "cheers drink alcohol toast", category: "Food & Drink" },
    Emoji { character: "🥂", name: "Clinking Glasses", keywords: "champagne toast cheers celebrate", category: "Food & Drink" },
    Emoji { character: "🍷", name: "Wine Glass", keywords: "drink alcohol red", category: "Food & Drink" },
    Emoji { character: "🍸", name: "Cocktail Glass", keywords: "drink alcohol martini", category: "Food & Drink" },
    Emoji { character: "🧊", name: "Ice", keywords: "cold cube frozen", category: "Food & Drink" },
    // ── Activities & Sports ────────────────────────────────────────
    Emoji { character: "⚽", name: "Soccer Ball", keywords: "football sport", category: "Activities" },
    Emoji { character: "🏀", name: "Basketball", keywords: "sport ball hoop", category: "Activities" },
    Emoji { character: "🏈", name: "American Football", keywords: "sport nfl", category: "Activities" },
    Emoji { character: "⚾", name: "Baseball", keywords: "sport ball", category: "Activities" },
    Emoji { character: "🎾", name: "Tennis", keywords: "sport ball racket", category: "Activities" },
    Emoji { character: "🏐", name: "Volleyball", keywords: "sport ball", category: "Activities" },
    Emoji { character: "🏓", name: "Ping Pong", keywords: "table tennis sport", category: "Activities" },
    Emoji { character: "🏸", name: "Badminton", keywords: "sport shuttlecock", category: "Activities" },
    Emoji { character: "🥊", name: "Boxing Glove", keywords: "fight sport punch", category: "Activities" },
    Emoji { character: "⛳", name: "Flag in Hole", keywords: "golf sport", category: "Activities" },
    Emoji { character: "🎯", name: "Bullseye", keywords: "target dart aim", category: "Activities" },
    Emoji { character: "🎮", name: "Video Game", keywords: "controller gaming play", category: "Activities" },
    Emoji { character: "🕹️", name: "Joystick", keywords: "game arcade", category: "Activities" },
    Emoji { character: "🎲", name: "Game Die", keywords: "dice random chance", category: "Activities" },
    Emoji { character: "🧩", name: "Puzzle Piece", keywords: "jigsaw game", category: "Activities" },
    Emoji { character: "♟️", name: "Chess Pawn", keywords: "game strategy", category: "Activities" },
    Emoji { character: "🎭", name: "Performing Arts", keywords: "theater drama masks", category: "Activities" },
    Emoji { character: "🎨", name: "Artist Palette", keywords: "paint art creative", category: "Activities" },
    Emoji { character: "🎬", name: "Clapper Board", keywords: "movie film cinema", category: "Activities" },
    Emoji { character: "🎤", name: "Microphone", keywords: "sing karaoke voice", category: "Activities" },
    Emoji { character: "🎧", name: "Headphone", keywords: "music audio listen", category: "Activities" },
    Emoji { character: "🎵", name: "Musical Note", keywords: "music sound melody", category: "Activities" },
    Emoji { character: "🎶", name: "Musical Notes", keywords: "music sound melody", category: "Activities" },
    Emoji { character: "🎹", name: "Musical Keyboard", keywords: "piano music keys", category: "Activities" },
    Emoji { character: "🎸", name: "Guitar", keywords: "music rock instrument", category: "Activities" },
    Emoji { character: "🎺", name: "Trumpet", keywords: "music brass instrument", category: "Activities" },
    Emoji { character: "🥁", name: "Drum", keywords: "music percussion beat", category: "Activities" },
    Emoji { character: "🎪", name: "Circus Tent", keywords: "carnival festival", category: "Activities" },
    Emoji { character: "🎉", name: "Party Popper", keywords: "celebrate confetti birthday tada", category: "Activities" },
    Emoji { character: "🎊", name: "Confetti Ball", keywords: "party celebrate", category: "Activities" },
    Emoji { character: "🎁", name: "Wrapped Gift", keywords: "present birthday christmas", category: "Activities" },
    Emoji { character: "🎄", name: "Christmas Tree", keywords: "holiday xmas", category: "Activities" },
    Emoji { character: "🎃", name: "Jack-O-Lantern", keywords: "halloween pumpkin", category: "Activities" },
    Emoji { character: "🎆", name: "Fireworks", keywords: "celebrate new year", category: "Activities" },
    Emoji { character: "🎇", name: "Sparkler", keywords: "fireworks celebrate", category: "Activities" },
    Emoji { character: "✨", name: "Sparkles", keywords: "shine glitter stars magic", category: "Activities" },
    Emoji { character: "🎀", name: "Ribbon", keywords: "bow decoration", category: "Activities" },
    Emoji { character: "🏆", name: "Trophy", keywords: "win award champion prize", category: "Activities" },
    Emoji { character: "🏅", name: "Sports Medal", keywords: "win award", category: "Activities" },
    Emoji { character: "🥇", name: "1st Place Medal", keywords: "gold first winner", category: "Activities" },
    Emoji { character: "🥈", name: "2nd Place Medal", keywords: "silver second", category: "Activities" },
    Emoji { character: "🥉", name: "3rd Place Medal", keywords: "bronze third", category: "Activities" },
    // ── Travel & Places ────────────────────────────────────────────
    Emoji { character: "🚗", name: "Automobile", keywords: "car drive vehicle", category: "Travel & Places" },
    Emoji { character: "🚕", name: "Taxi", keywords: "car cab ride", category: "Travel & Places" },
    Emoji { character: "🚌", name: "Bus", keywords: "vehicle transit", category: "Travel & Places" },
    Emoji { character: "🚎", name: "Trolleybus", keywords: "bus transit", category: "Travel & Places" },
    Emoji { character: "🚑", name: "Ambulance", keywords: "emergency medical hospital", category: "Travel & Places" },
    Emoji { character: "🚒", name: "Fire Engine", keywords: "truck emergency", category: "Travel & Places" },
    Emoji { character: "🚓", name: "Police Car", keywords: "cop law enforcement", category: "Travel & Places" },
    Emoji { character: "🚲", name: "Bicycle", keywords: "bike cycling ride", category: "Travel & Places" },
    Emoji { character: "✈️", name: "Airplane", keywords: "fly travel plane flight", category: "Travel & Places" },
    Emoji { character: "🚀", name: "Rocket", keywords: "space launch ship", category: "Travel & Places" },
    Emoji { character: "🛸", name: "Flying Saucer", keywords: "ufo alien space", category: "Travel & Places" },
    Emoji { character: "🚢", name: "Ship", keywords: "boat cruise ocean", category: "Travel & Places" },
    Emoji { character: "⛵", name: "Sailboat", keywords: "boat sailing sea", category: "Travel & Places" },
    Emoji { character: "🚂", name: "Locomotive", keywords: "train steam", category: "Travel & Places" },
    Emoji { character: "🏠", name: "House", keywords: "home building", category: "Travel & Places" },
    Emoji { character: "🏢", name: "Office Building", keywords: "work business", category: "Travel & Places" },
    Emoji { character: "🏥", name: "Hospital", keywords: "medical health doctor", category: "Travel & Places" },
    Emoji { character: "🏫", name: "School", keywords: "education building", category: "Travel & Places" },
    Emoji { character: "🏰", name: "Castle", keywords: "medieval fortress palace", category: "Travel & Places" },
    Emoji { character: "🗼", name: "Tokyo Tower", keywords: "japan landmark", category: "Travel & Places" },
    Emoji { character: "🗽", name: "Statue of Liberty", keywords: "america new york", category: "Travel & Places" },
    Emoji { character: "⛪", name: "Church", keywords: "religion building", category: "Travel & Places" },
    Emoji { character: "🕌", name: "Mosque", keywords: "islam religion", category: "Travel & Places" },
    Emoji { character: "🌍", name: "Globe Europe-Africa", keywords: "earth world planet", category: "Travel & Places" },
    Emoji { character: "🌎", name: "Globe Americas", keywords: "earth world planet", category: "Travel & Places" },
    Emoji { character: "🌏", name: "Globe Asia-Australia", keywords: "earth world planet", category: "Travel & Places" },
    Emoji { character: "🗺️", name: "World Map", keywords: "earth globe atlas", category: "Travel & Places" },
    Emoji { character: "🏔️", name: "Snow-Capped Mountain", keywords: "alps peak nature", category: "Travel & Places" },
    Emoji { character: "⛰️", name: "Mountain", keywords: "peak nature hike", category: "Travel & Places" },
    Emoji { character: "🌋", name: "Volcano", keywords: "eruption lava mountain", category: "Travel & Places" },
    Emoji { character: "🏖️", name: "Beach with Umbrella", keywords: "sand sea vacation", category: "Travel & Places" },
    Emoji { character: "🏕️", name: "Camping", keywords: "tent outdoor nature", category: "Travel & Places" },
    // ── Weather & Sky ──────────────────────────────────────────────
    Emoji { character: "☀️", name: "Sun", keywords: "sunny weather bright hot", category: "Travel & Places" },
    Emoji { character: "🌙", name: "Crescent Moon", keywords: "night moon", category: "Travel & Places" },
    Emoji { character: "⭐", name: "Star", keywords: "night sky favorite", category: "Travel & Places" },
    Emoji { character: "🌟", name: "Glowing Star", keywords: "shine sparkle night", category: "Travel & Places" },
    Emoji { character: "🌈", name: "Rainbow", keywords: "colorful weather pride", category: "Travel & Places" },
    Emoji { character: "☁️", name: "Cloud", keywords: "weather sky", category: "Travel & Places" },
    Emoji { character: "🌧️", name: "Cloud with Rain", keywords: "weather rainy", category: "Travel & Places" },
    Emoji { character: "⛈️", name: "Cloud with Lightning and Rain", keywords: "storm thunder weather", category: "Travel & Places" },
    Emoji { character: "❄️", name: "Snowflake", keywords: "snow winter cold ice", category: "Travel & Places" },
    Emoji { character: "🔥", name: "Fire", keywords: "flame hot lit burn", category: "Travel & Places" },
    Emoji { character: "💧", name: "Droplet", keywords: "water rain tear", category: "Travel & Places" },
    Emoji { character: "🌊", name: "Water Wave", keywords: "ocean sea surf", category: "Travel & Places" },
    // ── Objects ─────────────────────────────────────────────────────
    Emoji { character: "⌚", name: "Watch", keywords: "time clock wrist", category: "Objects" },
    Emoji { character: "📱", name: "Mobile Phone", keywords: "cell smartphone iphone", category: "Objects" },
    Emoji { character: "💻", name: "Laptop", keywords: "computer pc", category: "Objects" },
    Emoji { character: "⌨️", name: "Keyboard", keywords: "type computer input", category: "Objects" },
    Emoji { character: "🖥️", name: "Desktop Computer", keywords: "monitor screen pc", category: "Objects" },
    Emoji { character: "🖨️", name: "Printer", keywords: "print paper output", category: "Objects" },
    Emoji { character: "🖱️", name: "Computer Mouse", keywords: "click point", category: "Objects" },
    Emoji { character: "💽", name: "Computer Disk", keywords: "minidisk storage", category: "Objects" },
    Emoji { character: "💾", name: "Floppy Disk", keywords: "save storage oldschool", category: "Objects" },
    Emoji { character: "📷", name: "Camera", keywords: "photo picture", category: "Objects" },
    Emoji { character: "📹", name: "Video Camera", keywords: "film record", category: "Objects" },
    Emoji { character: "🎥", name: "Movie Camera", keywords: "film cinema", category: "Objects" },
    Emoji { character: "📺", name: "Television", keywords: "tv screen watch", category: "Objects" },
    Emoji { character: "📻", name: "Radio", keywords: "music audio fm am", category: "Objects" },
    Emoji { character: "🔔", name: "Bell", keywords: "notification alert ring", category: "Objects" },
    Emoji { character: "🔕", name: "Bell with Slash", keywords: "mute silent notification", category: "Objects" },
    Emoji { character: "📢", name: "Loudspeaker", keywords: "announcement megaphone volume", category: "Objects" },
    Emoji { character: "📣", name: "Megaphone", keywords: "announcement cheer", category: "Objects" },
    Emoji { character: "🔑", name: "Key", keywords: "lock password access", category: "Objects" },
    Emoji { character: "🔒", name: "Locked", keywords: "lock secure private password", category: "Objects" },
    Emoji { character: "🔓", name: "Unlocked", keywords: "lock open insecure", category: "Objects" },
    Emoji { character: "🔨", name: "Hammer", keywords: "tool build fix", category: "Objects" },
    Emoji { character: "🔧", name: "Wrench", keywords: "tool fix settings", category: "Objects" },
    Emoji { character: "🔩", name: "Nut and Bolt", keywords: "hardware tool fix", category: "Objects" },
    Emoji { character: "⚙️", name: "Gear", keywords: "settings cog mechanism", category: "Objects" },
    Emoji { character: "🧲", name: "Magnet", keywords: "attract magnetic", category: "Objects" },
    Emoji { character: "💡", name: "Light Bulb", keywords: "idea bright tip", category: "Objects" },
    Emoji { character: "🔦", name: "Flashlight", keywords: "light torch", category: "Objects" },
    Emoji { character: "🕯️", name: "Candle", keywords: "light fire", category: "Objects" },
    Emoji { character: "📖", name: "Open Book", keywords: "read study literature", category: "Objects" },
    Emoji { character: "📚", name: "Books", keywords: "read library study", category: "Objects" },
    Emoji { character: "📝", name: "Memo", keywords: "note write document", category: "Objects" },
    Emoji { character: "📄", name: "Page Facing Up", keywords: "document file", category: "Objects" },
    Emoji { character: "📁", name: "File Folder", keywords: "directory organize", category: "Objects" },
    Emoji { character: "📂", name: "Open File Folder", keywords: "directory organize", category: "Objects" },
    Emoji { character: "📅", name: "Calendar", keywords: "date schedule event", category: "Objects" },
    Emoji { character: "📊", name: "Bar Chart", keywords: "graph stats data analytics", category: "Objects" },
    Emoji { character: "📈", name: "Chart Increasing", keywords: "graph growth up stonks", category: "Objects" },
    Emoji { character: "📉", name: "Chart Decreasing", keywords: "graph decline down", category: "Objects" },
    Emoji { character: "📌", name: "Pushpin", keywords: "pin location mark", category: "Objects" },
    Emoji { character: "📎", name: "Paperclip", keywords: "attach clip", category: "Objects" },
    Emoji { character: "✂️", name: "Scissors", keywords: "cut clip", category: "Objects" },
    Emoji { character: "🗑️", name: "Wastebasket", keywords: "trash delete garbage bin", category: "Objects" },
    Emoji { character: "📦", name: "Package", keywords: "box shipping delivery", category: "Objects" },
    Emoji { character: "📧", name: "E-Mail", keywords: "email letter message envelope", category: "Objects" },
    Emoji { character: "📬", name: "Open Mailbox with Raised Flag", keywords: "email inbox mail", category: "Objects" },
    Emoji { character: "✉️", name: "Envelope", keywords: "letter mail email", category: "Objects" },
    Emoji { character: "💰", name: "Money Bag", keywords: "dollar cash rich", category: "Objects" },
    Emoji { character: "💳", name: "Credit Card", keywords: "payment money buy", category: "Objects" },
    Emoji { character: "💎", name: "Gem Stone", keywords: "diamond jewel crystal", category: "Objects" },
    Emoji { character: "🧪", name: "Test Tube", keywords: "science experiment lab", category: "Objects" },
    Emoji { character: "🔬", name: "Microscope", keywords: "science research zoom", category: "Objects" },
    Emoji { character: "🔭", name: "Telescope", keywords: "science astronomy space stars", category: "Objects" },
    Emoji { character: "💊", name: "Pill", keywords: "medicine drug health", category: "Objects" },
    Emoji { character: "🩹", name: "Adhesive Bandage", keywords: "bandaid heal wound", category: "Objects" },
    Emoji { character: "🛡️", name: "Shield", keywords: "protect defend guard security", category: "Objects" },
    Emoji { character: "🪄", name: "Magic Wand", keywords: "wizard spell magic", category: "Objects" },
    // ── Symbols ─────────────────────────────────────────────────────
    Emoji { character: "❌", name: "Cross Mark", keywords: "no wrong error delete", category: "Symbols" },
    Emoji { character: "⭕", name: "Hollow Red Circle", keywords: "circle correct right", category: "Symbols" },
    Emoji { character: "✅", name: "Check Mark Button", keywords: "yes done ok agree complete", category: "Symbols" },
    Emoji { character: "☑️", name: "Check Box with Check", keywords: "done complete", category: "Symbols" },
    Emoji { character: "✔️", name: "Check Mark", keywords: "yes done correct", category: "Symbols" },
    Emoji { character: "❗", name: "Red Exclamation Mark", keywords: "warning important alert bang", category: "Symbols" },
    Emoji { character: "❓", name: "Red Question Mark", keywords: "what help confused", category: "Symbols" },
    Emoji { character: "‼️", name: "Double Exclamation Mark", keywords: "warning surprised", category: "Symbols" },
    Emoji { character: "⚠️", name: "Warning", keywords: "caution alert danger", category: "Symbols" },
    Emoji { character: "🚫", name: "Prohibited", keywords: "no stop forbidden ban", category: "Symbols" },
    Emoji { character: "🔴", name: "Red Circle", keywords: "dot round", category: "Symbols" },
    Emoji { character: "🟠", name: "Orange Circle", keywords: "dot round", category: "Symbols" },
    Emoji { character: "🟡", name: "Yellow Circle", keywords: "dot round", category: "Symbols" },
    Emoji { character: "🟢", name: "Green Circle", keywords: "dot round", category: "Symbols" },
    Emoji { character: "🔵", name: "Blue Circle", keywords: "dot round", category: "Symbols" },
    Emoji { character: "🟣", name: "Purple Circle", keywords: "dot round", category: "Symbols" },
    Emoji { character: "⚫", name: "Black Circle", keywords: "dot round", category: "Symbols" },
    Emoji { character: "⚪", name: "White Circle", keywords: "dot round", category: "Symbols" },
    Emoji { character: "🟥", name: "Red Square", keywords: "block", category: "Symbols" },
    Emoji { character: "🟧", name: "Orange Square", keywords: "block", category: "Symbols" },
    Emoji { character: "🟨", name: "Yellow Square", keywords: "block", category: "Symbols" },
    Emoji { character: "🟩", name: "Green Square", keywords: "block", category: "Symbols" },
    Emoji { character: "🟦", name: "Blue Square", keywords: "block", category: "Symbols" },
    Emoji { character: "🟪", name: "Purple Square", keywords: "block", category: "Symbols" },
    Emoji { character: "⬛", name: "Black Large Square", keywords: "block", category: "Symbols" },
    Emoji { character: "⬜", name: "White Large Square", keywords: "block", category: "Symbols" },
    Emoji { character: "▶️", name: "Play Button", keywords: "start media forward", category: "Symbols" },
    Emoji { character: "⏸️", name: "Pause Button", keywords: "stop media wait", category: "Symbols" },
    Emoji { character: "⏹️", name: "Stop Button", keywords: "media end", category: "Symbols" },
    Emoji { character: "⏩", name: "Fast-Forward Button", keywords: "skip speed", category: "Symbols" },
    Emoji { character: "⏪", name: "Fast Reverse Button", keywords: "rewind back", category: "Symbols" },
    Emoji { character: "🔀", name: "Shuffle Tracks Button", keywords: "random mix", category: "Symbols" },
    Emoji { character: "🔁", name: "Repeat Button", keywords: "loop again", category: "Symbols" },
    Emoji { character: "🔂", name: "Repeat Single Button", keywords: "loop once", category: "Symbols" },
    Emoji { character: "➕", name: "Plus", keywords: "add math", category: "Symbols" },
    Emoji { character: "➖", name: "Minus", keywords: "subtract math", category: "Symbols" },
    Emoji { character: "➗", name: "Divide", keywords: "division math", category: "Symbols" },
    Emoji { character: "✖️", name: "Multiply", keywords: "times math", category: "Symbols" },
    Emoji { character: "♾️", name: "Infinity", keywords: "forever unlimited loop", category: "Symbols" },
    Emoji { character: "💲", name: "Heavy Dollar Sign", keywords: "money cash price", category: "Symbols" },
    Emoji { character: "©️", name: "Copyright", keywords: "ip legal", category: "Symbols" },
    Emoji { character: "®️", name: "Registered", keywords: "trademark legal", category: "Symbols" },
    Emoji { character: "™️", name: "Trade Mark", keywords: "brand legal intellectual property", category: "Symbols" },
    Emoji { character: "🔗", name: "Link", keywords: "chain url hyperlink", category: "Symbols" },
    Emoji { character: "⬆️", name: "Up Arrow", keywords: "direction north", category: "Symbols" },
    Emoji { character: "⬇️", name: "Down Arrow", keywords: "direction south", category: "Symbols" },
    Emoji { character: "⬅️", name: "Left Arrow", keywords: "direction west back", category: "Symbols" },
    Emoji { character: "➡️", name: "Right Arrow", keywords: "direction east forward next", category: "Symbols" },
    Emoji { character: "↩️", name: "Right Arrow Curving Left", keywords: "return back undo", category: "Symbols" },
    Emoji { character: "↪️", name: "Left Arrow Curving Right", keywords: "forward redo", category: "Symbols" },
    Emoji { character: "🔄", name: "Counterclockwise Arrows Button", keywords: "refresh sync reload update", category: "Symbols" },
    Emoji { character: "ℹ️", name: "Information", keywords: "info help about", category: "Symbols" },
    // ── Flags ───────────────────────────────────────────────────────
    Emoji { character: "🏳️", name: "White Flag", keywords: "surrender peace", category: "Flags" },
    Emoji { character: "🏴", name: "Black Flag", keywords: "pirate", category: "Flags" },
    Emoji { character: "🏁", name: "Chequered Flag", keywords: "racing finish checkered", category: "Flags" },
    Emoji { character: "🚩", name: "Triangular Flag", keywords: "red flag warning marker", category: "Flags" },
    Emoji { character: "🏳️‍🌈", name: "Rainbow Flag", keywords: "pride lgbtq gay", category: "Flags" },
    Emoji { character: "🏳️‍⚧️", name: "Transgender Flag", keywords: "trans lgbtq pride", category: "Flags" },
    Emoji { character: "🇺🇸", name: "Flag: United States", keywords: "usa america us", category: "Flags" },
    Emoji { character: "🇬🇧", name: "Flag: United Kingdom", keywords: "uk british england", category: "Flags" },
    Emoji { character: "🇫🇷", name: "Flag: France", keywords: "french", category: "Flags" },
    Emoji { character: "🇩🇪", name: "Flag: Germany", keywords: "german deutsch", category: "Flags" },
    Emoji { character: "🇯🇵", name: "Flag: Japan", keywords: "japanese", category: "Flags" },
    Emoji { character: "🇨🇳", name: "Flag: China", keywords: "chinese", category: "Flags" },
    Emoji { character: "🇰🇷", name: "Flag: South Korea", keywords: "korean", category: "Flags" },
    Emoji { character: "🇮🇳", name: "Flag: India", keywords: "indian", category: "Flags" },
    Emoji { character: "🇧🇷", name: "Flag: Brazil", keywords: "brazilian", category: "Flags" },
    Emoji { character: "🇨🇦", name: "Flag: Canada", keywords: "canadian maple", category: "Flags" },
    Emoji { character: "🇦🇺", name: "Flag: Australia", keywords: "australian", category: "Flags" },
    Emoji { character: "🇪🇸", name: "Flag: Spain", keywords: "spanish", category: "Flags" },
    Emoji { character: "🇮🇹", name: "Flag: Italy", keywords: "italian", category: "Flags" },
    Emoji { character: "🇲🇽", name: "Flag: Mexico", keywords: "mexican", category: "Flags" },
    Emoji { character: "🇷🇺", name: "Flag: Russia", keywords: "russian", category: "Flags" },
    Emoji { character: "🇫🇮", name: "Flag: Finland", keywords: "finnish suomi", category: "Flags" },
    Emoji { character: "🇸🇪", name: "Flag: Sweden", keywords: "swedish", category: "Flags" },
    Emoji { character: "🇳🇴", name: "Flag: Norway", keywords: "norwegian", category: "Flags" },
    Emoji { character: "🇩🇰", name: "Flag: Denmark", keywords: "danish", category: "Flags" },
    Emoji { character: "🇺🇦", name: "Flag: Ukraine", keywords: "ukrainian", category: "Flags" },
    Emoji { character: "🇵🇱", name: "Flag: Poland", keywords: "polish", category: "Flags" },
    Emoji { character: "🇳🇱", name: "Flag: Netherlands", keywords: "dutch holland", category: "Flags" },
    Emoji { character: "🇧🇪", name: "Flag: Belgium", keywords: "belgian", category: "Flags" },
    Emoji { character: "🇨🇭", name: "Flag: Switzerland", keywords: "swiss", category: "Flags" },
    Emoji { character: "🇦🇹", name: "Flag: Austria", keywords: "austrian", category: "Flags" },
    Emoji { character: "🇵🇹", name: "Flag: Portugal", keywords: "portuguese", category: "Flags" },
    Emoji { character: "🇬🇷", name: "Flag: Greece", keywords: "greek", category: "Flags" },
    Emoji { character: "🇹🇷", name: "Flag: Turkey", keywords: "turkish", category: "Flags" },
    Emoji { character: "🇮🇱", name: "Flag: Israel", keywords: "israeli", category: "Flags" },
    Emoji { character: "🇪🇬", name: "Flag: Egypt", keywords: "egyptian", category: "Flags" },
    Emoji { character: "🇿🇦", name: "Flag: South Africa", keywords: "south african", category: "Flags" },
    Emoji { character: "🇳🇬", name: "Flag: Nigeria", keywords: "nigerian", category: "Flags" },
    Emoji { character: "🇰🇪", name: "Flag: Kenya", keywords: "kenyan", category: "Flags" },
    Emoji { character: "🇦🇷", name: "Flag: Argentina", keywords: "argentinian", category: "Flags" },
    Emoji { character: "🇨🇱", name: "Flag: Chile", keywords: "chilean", category: "Flags" },
    Emoji { character: "🇨🇴", name: "Flag: Colombia", keywords: "colombian", category: "Flags" },
    Emoji { character: "🇹🇭", name: "Flag: Thailand", keywords: "thai", category: "Flags" },
    Emoji { character: "🇻🇳", name: "Flag: Vietnam", keywords: "vietnamese", category: "Flags" },
    Emoji { character: "🇮🇩", name: "Flag: Indonesia", keywords: "indonesian", category: "Flags" },
    Emoji { character: "🇵🇭", name: "Flag: Philippines", keywords: "filipino", category: "Flags" },
    Emoji { character: "🇸🇬", name: "Flag: Singapore", keywords: "singaporean", category: "Flags" },
    Emoji { character: "🇲🇾", name: "Flag: Malaysia", keywords: "malaysian", category: "Flags" },
    Emoji { character: "🇳🇿", name: "Flag: New Zealand", keywords: "kiwi", category: "Flags" },
    Emoji { character: "🇪🇪", name: "Flag: Estonia", keywords: "estonian", category: "Flags" },
    Emoji { character: "🇱🇻", name: "Flag: Latvia", keywords: "latvian", category: "Flags" },
    Emoji { character: "🇱🇹", name: "Flag: Lithuania", keywords: "lithuanian", category: "Flags" },
    Emoji { character: "🇮🇪", name: "Flag: Ireland", keywords: "irish", category: "Flags" },
    Emoji { character: "🇮🇸", name: "Flag: Iceland", keywords: "icelandic", category: "Flags" },
];
